# Generated by Django 4.2.26 on 2025-11-17 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField(blank=True, null=True)),
                ('provisional_diagnosis', models.TextField()),
                ('final_diagnosis', models.TextField(blank=True)),
                ('treatment_duration', models.CharField(blank=True, max_length=120)),
                ('treatment_frequency', models.CharField(blank=True, max_length=120)),
                ('lab_tests_done', models.TextField(blank=True)),
                ('next_of_kin_name', models.CharField(max_length=120)),
                ('next_of_kin_contact', models.CharField(max_length=60)),
                ('allergies', models.TextField(blank=True)),
                ('contraindications', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('discharged', 'Discharged'), ('closed', 'Closed')], default='active', max_length=32)),
            ],
            options={
                'ordering': ('-admission_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ClinicalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('documented_at', models.DateTimeField()),
                ('systolic_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('diastolic_bp', models.PositiveIntegerField(blank=True, null=True)),
                ('pulse', models.PositiveIntegerField(blank=True, null=True)),
                ('respiration_rate', models.PositiveIntegerField(blank=True, null=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('oxygen_saturation', models.PositiveIntegerField(blank=True, null=True)),
                ('treatment_details', models.TextField()),
                ('treatment_route', models.CharField(blank=True, max_length=120)),
                ('complaints', models.TextField(blank=True)),
                ('remarks', models.TextField(blank=True)),
                ('recorded_by_name', models.CharField(max_length=150)),
                ('recorded_by_role', models.CharField(max_length=150)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clinical_notes', to='care.admission')),
            ],
            options={
                'ordering': ('-documented_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=120)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('last_name', 'first_name'),
            },
        ),
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admissions', to='care.patient'),
        ),
        migrations.CreateModel(
            name='ClinicalNoteVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('payload', models.JSONField()),
                ('change_reason', models.CharField(max_length=255)),
                ('changed_by_name', models.CharField(max_length=150)),
                ('changed_by_role', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='care.clinicalnote')),
            ],
            options={
                'ordering': ('-version_number',),
                'unique_together': {('note', 'version_number')},
            },
        ),
    ]
