# Generated by Django 5.2.8 on 2025-11-18 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_key', models.CharField(choices=[('dashboard', 'Dashboard'), ('patients', 'Patient Management'), ('appointments', 'Appointments & Scheduling'), ('billing', 'Billing & Finance'), ('pharmacy', 'Pharmacy Management'), ('laboratory', 'Laboratory & Diagnostics'), ('inventory', 'Inventory & Supply Chain'), ('reports', 'Reporting & Analytics'), ('support', 'Customer Support')], max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_accesses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Module access',
                'verbose_name_plural': 'Module access',
                'unique_together': {('user', 'module_key')},
            },
        ),
    ]
