# Generated by Django 5.2.8 on 2025-11-25 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0005_triageentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triageentry',
            name='status',
            field=models.CharField(choices=[('triage', 'In Triage'), ('lab_done', 'Lab Completed'), ('treatment', 'Ready for Treatment'), ('discharged', 'Discharged')], default='triage', max_length=24),
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('test_type', models.CharField(max_length=120)),
                ('summary', models.TextField()),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('recorded_at', models.DateTimeField()),
                ('recorded_by_name', models.CharField(max_length=150)),
                ('recorded_by_role', models.CharField(max_length=150)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_results', to='care.admission')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_results', to='care.patient')),
                ('triage_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results', to='care.triageentry')),
            ],
            options={
                'ordering': ('-recorded_at', '-id'),
            },
        ),
    ]
