# Generated by Django 5.2.8 on 2025-11-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0003_admission_review_date_patient_patient_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleaccess',
            name='module_key',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('triage', 'Triage'), ('patients', 'Patient Management'), ('appointments', 'Appointments & Scheduling'), ('billing', 'Billing & Finance'), ('pharmacy', 'Pharmacy Management'), ('laboratory', 'Laboratory & Diagnostics'), ('inventory', 'Inventory & Supply Chain'), ('reports', 'Reporting & Analytics'), ('support', 'Customer Support')], max_length=32),
        ),
    ]
