# Generated by Django 5.2.8 on 2025-11-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0004_alter_moduleaccess_module_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='TriageEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.PositiveIntegerField(default=0)),
                ('sex', models.CharField(blank=True, max_length=30)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('arrival_method', models.CharField(blank=True, max_length=60)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('admission_date', models.DateField()),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=30)),
                ('symptoms', models.TextField(blank=True)),
                ('allergies', models.TextField(blank=True)),
                ('temperature_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(choices=[('triage', 'In Triage'), ('treatment', 'Ready for Treatment'), ('discharged', 'Discharged')], default='triage', max_length=24)),
            ],
            options={
                'ordering': ('-admission_date', '-id'),
            },
        ),
    ]
