# Generated by Django 5.2.8 on 2025-12-27 17:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care', '0006_alter_triageentry_status_labresult'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('complete', 'Complete'), ('verified', 'Verified')], default='complete', max_length=24),
        ),
        migrations.AlterField(
            model_name='moduleaccess',
            name='module_key',
            field=models.CharField(choices=[('dashboard', 'Dashboard'), ('triage', 'Triage'), ('patients', 'Patient Management'), ('appointments', 'Appointments & Scheduling'), ('billing', 'Billing & Finance'), ('pharmacy', 'Pharmacy Management'), ('laboratory', 'Laboratory & Diagnostics'), ('inventory', 'Inventory & Supply Chain'), ('reports', 'Reporting & Analytics'), ('support', 'Customer Support'), ('consultation', 'Consultation & Review')], max_length=32),
        ),
        migrations.CreateModel(
            name='CarePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('finalized', 'Finalized')], default='draft', max_length=24)),
                ('version', models.PositiveIntegerField(default=1)),
                ('assessment', models.CharField(blank=True, max_length=255)),
                ('plan_items', models.JSONField(blank=True, default=dict)),
                ('next_review_at', models.DateTimeField(blank=True, null=True)),
                ('escalation_criteria', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='care_plans', to='care.admission')),
                ('authored_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='care_plans', to=settings.AUTH_USER_MODEL)),
                ('supersedes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_by', to='care.careplan')),
            ],
            options={
                'ordering': ('-version', '-created_at'),
                'unique_together': {('admission', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ConsultationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('event_type', models.CharField(max_length=64)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField()),
                ('actor_name', models.CharField(blank=True, max_length=150)),
                ('actor_role', models.CharField(blank=True, max_length=150)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_events', to='care.admission')),
            ],
            options={
                'ordering': ('-occurred_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=24)),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent')], default='routine', max_length=16)),
                ('order_items', models.JSONField(blank=True, default=list)),
                ('clinical_question', models.CharField(blank=True, max_length=255)),
                ('notes_to_lab', models.TextField(blank=True)),
                ('policy_bypass', models.BooleanField(default=False, help_text='True if lab proceeded without formal order.')),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lab_orders', to='care.admission')),
                ('ordered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to=settings.AUTH_USER_MODEL)),
                ('triage_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_orders', to='care.triageentry')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='ConsultationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('task_type', models.CharField(choices=[('new_plan', 'New Care Plan'), ('results_ready', 'Results Ready'), ('ack_required', 'Acknowledgement Required')], max_length=32)),
                ('target_role', models.CharField(blank=True, max_length=64)),
                ('status', models.CharField(choices=[('open', 'Open'), ('acknowledged', 'Acknowledged'), ('closed', 'Closed')], default='open', max_length=24)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_tasks', to=settings.AUTH_USER_MODEL)),
                ('admission', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultation_tasks', to='care.admission')),
                ('care_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='care.careplan')),
                ('lab_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='care.laborder')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.AddField(
            model_name='labresult',
            name='lab_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='care.laborder'),
        ),
    ]
